package ihms;

import donnees.Enseignant;
import donnees.Etudiant;
import donnees.Utilisateur;
import java.io.IOException;

import javax.swing.JOptionPane;
import utilitaires_ihms.GestionNotes;
import utilitaires_ihms.GestionVerrou;
import utilitaires_ihms.IdentificationException;

public class IhmGestionNotes extends javax.swing.JFrame {

  /**
   * Creates new form IhmGestionNotes
   */
  public IhmGestionNotes() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelIdentifiant = new javax.swing.JLabel();
        txtIdentifiant = new javax.swing.JTextField();
        labelMotDePasse = new javax.swing.JLabel();
        txtMotDePasse = new javax.swing.JTextField();
        btnSeConnecter = new javax.swing.JButton();
        btnQuitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(255, 51, 51));
        setSize(new java.awt.Dimension(500, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion de notes");

        labelIdentifiant.setText("Identifiant");

        labelMotDePasse.setText("Mot de passe");

        btnSeConnecter.setText("Se connecter");
        btnSeConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeConnecterAction(evt);
            }
        });

        btnQuitter.setText("Quitter");
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMotDePasse)
                            .addComponent(labelIdentifiant))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSeConnecter))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnQuitter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdentifiant)
                    .addComponent(txtIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeConnecter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMotDePasse)
                    .addComponent(txtMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuitter))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void btnSeConnecterAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeConnecterAction
    String identifiant = txtIdentifiant.getText();
    String motDePasse = txtMotDePasse.getText();
    if(identifiant.equals("") || motDePasse.equals(""))
      JOptionPane.showMessageDialog(this, "Identifiant ou mot de passe non saisi(s) ! ");
    else try {
      Utilisateur  utilisateur = GestionNotes.connecter(identifiant, motDePasse);
      // Connexion réussie : fermer l'ihm GestionNote puis créer et afficher l'ihm Enseignant
      // ou Etudiant selon le type d'utilisateur
      this.setVisible(false);
      if (utilisateur instanceof Enseignant) 
          new IhmEnseignant((Enseignant)utilisateur).setVisible(true);
      else if(utilisateur instanceof Etudiant) 
          new IhmEtudiant((Etudiant)utilisateur).setVisible(true); 
      else {
          // Normalement, cela ne se produira jamais
          System.out.println("Type d'utilisateur non identifié ! Application arrêtée.");
          System.exit(0);
      }
    }
    catch(IdentificationException e) {
      JOptionPane.showMessageDialog(this, "Identifiant ou mot de passe incorrect(s) !");
    }
  }//GEN-LAST:event_btnSeConnecterAction

     
  private void btnQuitterAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterAction
    // Lever le verrou sur les données avant de quitter l'application
    try {
      GestionVerrou.deVerrouiller();
      System.out.println("Application arrêtée !");
      System.exit(0); // Tout arrêter
    }
    catch(IOException e) { 
      System.out.println("Erreur lors du déverrouillage des données !"); }
  }//GEN-LAST:event_btnQuitterAction

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    // Lever le verrou sur les données avant de quitter l'application
    try {
      GestionVerrou.deVerrouiller();
      System.out.println("Application arrêtée !");
    }
    catch(IOException e) { 
      System.out.println("Erreur lors du déverrouillage des données !"); }
  }//GEN-LAST:event_formWindowClosing

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    try {
      // 1. Attendre si nécessaire que le verrou sur l'application soit levé.
      if (GestionVerrou.verrouFerme()) {
        System.out.println("Application en cours d'utilisation. Attendez...");
        while (GestionVerrou.verrouFerme());
      }
      // 2. Le verrouillage étant levé, verrouiller et charger les données
      GestionVerrou.verrouiller();
      GestionNotes.chargerDonnees();
      // 3. Créer une instance de l'Ihm et l'afficher
      new IhmGestionNotes().setVisible(true);
      System.out.println("Application démarrée !");
    }    
    catch(Exception e) {
      System.out.println("Erreur de lancement "+e);
    }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuitter;
    private javax.swing.JButton btnSeConnecter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelIdentifiant;
    private javax.swing.JLabel labelMotDePasse;
    private javax.swing.JTextField txtIdentifiant;
    private javax.swing.JTextField txtMotDePasse;
    // End of variables declaration//GEN-END:variables
}
