
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author quentin.costes
 */
public class frame extends javax.swing.JFrame {

    /**
     * Creates new form frame
     */
    public frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radio = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        convertir = new javax.swing.JButton();
        radioEuro = new javax.swing.JRadioButton();
        radioDollar = new javax.swing.JRadioButton();
        devise = new javax.swing.JLabel();
        montantConverti = new javax.swing.JTextField();
        montantAConvertir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Montant a convertir");

        jLabel2.setText("montant coverti");

        convertir.setText("Convertir");
        convertir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convertirMouseClicked(evt);
            }
        });
        convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirActionPerformed(evt);
            }
        });

        radio.add(radioEuro);
        radioEuro.setText("€");
        radioEuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioEuroMouseClicked(evt);
            }
        });
        radioEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEuroActionPerformed(evt);
            }
        });

        radio.add(radioDollar);
        radioDollar.setText("$");
        radioDollar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioDollarMouseClicked(evt);
            }
        });

        montantConverti.setEditable(false);
        montantConverti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montantConvertiActionPerformed(evt);
            }
        });

        montantAConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montantAConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(convertir)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(montantAConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(montantConverti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioEuro)
                        .addGap(18, 18, 18)
                        .addComponent(radioDollar))
                    .addComponent(devise, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(montantAConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioEuro)
                    .addComponent(radioDollar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(montantConverti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(devise))
                .addGap(18, 18, 18)
                .addComponent(convertir)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void montantAConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montantAConvertirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montantAConvertirActionPerformed

    private void radioEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEuroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEuroActionPerformed

    private void montantConvertiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montantConvertiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montantConvertiActionPerformed

    private void convertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_convertirActionPerformed

    private void convertirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertirMouseClicked
        double converti;
        if (this.radioEuro.isSelected()) {
            try {
                converti = Double.parseDouble(this.montantAConvertir.getText());
                converti = 1.1703 * converti;
            } catch (Exception e) {
                converti = 0;
                JOptionPane.showMessageDialog(this, "Entrée incorrecte");
            }
            this.montantConverti.setText("" + String.format("%.2f", converti));
        } else if (this.radioDollar.isSelected()) {
            try {
                converti = Double.parseDouble(this.montantAConvertir.getText());
                converti =  converti / 1.1703;
            } catch (Exception e) {
                converti = 0;
                JOptionPane.showMessageDialog(this, "Entrée incorrecte");
            }
            this.montantConverti.setText("" + String.format("%.2f", converti));
        } else {
            JOptionPane.showMessageDialog(this, "veuillez cochez une devise");
        }
    }//GEN-LAST:event_convertirMouseClicked

    private void radioEuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioEuroMouseClicked
        this.devise.setText("$");
    }//GEN-LAST:event_radioEuroMouseClicked

    private void radioDollarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioDollarMouseClicked
        this.devise.setText("€");
    }//GEN-LAST:event_radioDollarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertir;
    private javax.swing.JLabel devise;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField montantAConvertir;
    private javax.swing.JTextField montantConverti;
    private javax.swing.ButtonGroup radio;
    private javax.swing.JRadioButton radioDollar;
    private javax.swing.JRadioButton radioEuro;
    // End of variables declaration//GEN-END:variables
}
