package chatuser;

import interfaces_remote.ChatRoom;
import java.rmi.Naming;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;

public class IHMChatUser extends javax.swing.JFrame {
    
    private ChatUserImpl chatUser;
    private ChatRoom chatRoom;
    private String pseudo;

    /**
     * Crée une instance de IhmChatUser et une instance de ChatUserImpl et les relie.
     * Bloque txtMessageAenvoyer, boutonEnvoyer et boutonDeconnecter.
     */
    public IHMChatUser() throws RemoteException {
        initComponents();
        chatUser = new ChatUserImpl(this);
        txtMessageAenvoyer.setEnabled(false);
        boutonEnvoyer.setEnabled(false);
        boutonDeconnecter.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUrlChatroom = new javax.swing.JTextField();
        boutonConnecter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessageAenvoyer = new javax.swing.JTextArea();
        boutonEnvoyer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMessagesChatroom = new javax.swing.JTextArea();
        boutonDeconnecter = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPseudo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Url Chatroom");

        boutonConnecter.setText("Connecter");
        boutonConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonConnecterActionPerformed(evt);
            }
        });

        jLabel2.setText("Message à envoyer");

        txtMessageAenvoyer.setColumns(20);
        txtMessageAenvoyer.setRows(5);
        jScrollPane1.setViewportView(txtMessageAenvoyer);

        boutonEnvoyer.setText("Envoyer");
        boutonEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonEnvoyerActionPerformed(evt);
            }
        });

        jLabel3.setText("Messages Chatroom");

        txtMessagesChatroom.setEditable(false);
        txtMessagesChatroom.setColumns(20);
        txtMessagesChatroom.setRows(5);
        jScrollPane2.setViewportView(txtMessagesChatroom);

        boutonDeconnecter.setText("Déconnecter");
        boutonDeconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonDeconnecterActionPerformed(evt);
            }
        });

        jLabel4.setText("Pseudo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPseudo)
                                        .addComponent(txtUrlChatroom))))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(boutonDeconnecter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boutonEnvoyer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(boutonConnecter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2))
                .addGap(5, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUrlChatroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(boutonConnecter)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(boutonEnvoyer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(boutonDeconnecter)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Rechercher dans RMI l'objet ChatRoom dont l'url a été saisie dans txtUrlChatroom. 
     * Si pas d'erreur, mémoriser l'objet dans l'attribut chatRoom puis appeller 
     * chatRoom.connecter() avec le pseudo saisi dans txtPseudo. Si pas d'erreur, mémoriser
     * le pseudo dans l'attribut pseudo, bloquer txtUrlChatroom, txtPseudo et boutonConnecter,
     * boutonConnecter et débloquer txtMessageAenvoyer, boutonEnvoyer et boutonDeconnecter. 
     * En cas d'erreur, afficher un message.
     */
    private void boutonConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonConnecterActionPerformed
        if (txtUrlChatroom.getText().equals("")||txtPseudo.getText().equals(""))
            JOptionPane.showMessageDialog(this, "URL chatroom ou pseudo non saisi(s) !");
        else
        try {
            chatRoom = (ChatRoom)Naming.lookup(txtUrlChatroom.getText());
            chatRoom.connecter(chatUser, txtPseudo.getText());
            pseudo = txtPseudo.getText();
            txtUrlChatroom.setEnabled(false);
            txtPseudo.setEnabled(false);
            boutonConnecter.setEnabled(false);
            txtMessageAenvoyer.setEnabled(true);
            boutonEnvoyer.setEnabled(true);
            boutonDeconnecter.setEnabled(true);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur : "+e);    
                }
    }//GEN-LAST:event_boutonConnecterActionPerformed

    /**
     *  Appelle chatRoom.poster() avec le texte saisi dans txtMessageAenvoyer.
     */
    private void boutonEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonEnvoyerActionPerformed
        if(txtMessageAenvoyer.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Aucun message saisi !");
        else
            try {
                chatRoom.poster(txtMessageAenvoyer.getText(), pseudo);
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur : "+e);
            }
    }//GEN-LAST:event_boutonEnvoyerActionPerformed
    private void quitter() {
      try {
        if(chatRoom != null) chatRoom.deconnecter(pseudo);
        System.exit(0);
      }
      catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur : "+e);
      }
    }
    /**
     * Appelle chatRoom.deconnecter(pseudo).
     */
    private void boutonDeconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonDeconnecterActionPerformed
      quitter();
    }//GEN-LAST:event_boutonDeconnecterActionPerformed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      quitter();
  }//GEN-LAST:event_formWindowClosing

    /**
     * Affiche message dans txtMessagesChatroom.
     */
    public void afficher(String message) {
      txtMessagesChatroom.setText(message+"\n"+txtMessagesChatroom.getText());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMChatUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMChatUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMChatUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMChatUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new IHMChatUser().setVisible(true);
                }
                catch(RemoteException e) {
                    System.out.println("Lancement impossible : "+e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonConnecter;
    private javax.swing.JButton boutonDeconnecter;
    private javax.swing.JButton boutonEnvoyer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtMessageAenvoyer;
    private javax.swing.JTextArea txtMessagesChatroom;
    private javax.swing.JTextField txtPseudo;
    private javax.swing.JTextField txtUrlChatroom;
    // End of variables declaration//GEN-END:variables
}
